package ng.com.magbel.token;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TokenAuthentication", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/wsdl/TokenAuthentication.asmx.wsdl")
public class TokenAuthentication
    extends Service
{

    private final static URL TOKENAUTHENTICATION_WSDL_LOCATION;
    private final static WebServiceException TOKENAUTHENTICATION_EXCEPTION;
    private final static QName TOKENAUTHENTICATION_QNAME = new QName("http://tempuri.org/", "TokenAuthentication");

    static {  
        URL url = null;
        WebServiceException e = null;
        Properties prop = new Properties();
        File file = new File("C:\\Property\\LegendPlus.properties");
        try {
         FileInputStream input = new FileInputStream(file);
         prop.load(input);
    	
         String soapEndpointUrl = prop.getProperty("endPointUrl");
         
         System.out.println("The url is : " + soapEndpointUrl);
    	
            url = new URL(soapEndpointUrl);
        } catch (IOException ex) {
            e = new WebServiceException(ex);
        }
        TOKENAUTHENTICATION_WSDL_LOCATION = url;
        TOKENAUTHENTICATION_EXCEPTION = e;
    }

    public TokenAuthentication() {
        super(__getWsdlLocation(), TOKENAUTHENTICATION_QNAME);
    }

    public TokenAuthentication(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENAUTHENTICATION_QNAME, features);
    }

    public TokenAuthentication(URL wsdlLocation) {
        super(wsdlLocation, TOKENAUTHENTICATION_QNAME);
    }

    public TokenAuthentication(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENAUTHENTICATION_QNAME, features);
    }

    public TokenAuthentication(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenAuthentication(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenAuthenticationSoap
     */
    @WebEndpoint(name = "TokenAuthenticationSoap")
    public TokenAuthenticationSoap getTokenAuthenticationSoap() {
        return super.getPort(new QName("http://tempuri.org/", "TokenAuthenticationSoap"), TokenAuthenticationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenAuthenticationSoap
     */
    @WebEndpoint(name = "TokenAuthenticationSoap")
    public TokenAuthenticationSoap getTokenAuthenticationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "TokenAuthenticationSoap"), TokenAuthenticationSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns TokenAuthenticationSoap
     */
    @WebEndpoint(name = "TokenAuthenticationSoap12")
    public TokenAuthenticationSoap getTokenAuthenticationSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "TokenAuthenticationSoap12"), TokenAuthenticationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenAuthenticationSoap
     */
    @WebEndpoint(name = "TokenAuthenticationSoap12")
    public TokenAuthenticationSoap getTokenAuthenticationSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "TokenAuthenticationSoap12"), TokenAuthenticationSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENAUTHENTICATION_EXCEPTION!= null) {
            throw TOKENAUTHENTICATION_EXCEPTION;
        }
        return TOKENAUTHENTICATION_WSDL_LOCATION;
    }

}
