
package ng.com.magbel.token;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TokenAuthenticationSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenAuthenticationSoap {


    /**
     * 
     * @param staffId
     * @param tokenCode
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AuthenticateToken", action = "http://tempuri.org/AuthenticateToken")
    @WebResult(name = "AuthenticateTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AuthenticateToken", targetNamespace = "http://tempuri.org/", className = "ng.com.magbel.token.AuthenticateToken")
    @ResponseWrapper(localName = "AuthenticateTokenResponse", targetNamespace = "http://tempuri.org/", className = "ng.com.magbel.token.AuthenticateTokenResponse")
    public boolean authenticateToken(
        @WebParam(name = "staffId", targetNamespace = "http://tempuri.org/")
        String staffId,
        @WebParam(name = "tokenCode", targetNamespace = "http://tempuri.org/")
        String tokenCode,
        @WebParam(name = "AppID", targetNamespace = "http://tempuri.org/")
        String AppID, 
        @WebParam(name = "AppKey", targetNamespace = "http://tempuri.org/")
        String AppKey);

}
